version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - C:\'Program Files'\MySQL\centralerros_data:/var/lib/mysql
volumes:
  centralerros_data: